#!/bin/bash
set -uo pipefail
trap 's=$?; echo "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR
IFS=$'\n\t'
uname -r
ls
apt-get update
apt install git python3-pip sox libsox-fmt-all flac libportaudio2 libatlas3-base libpulse0 libasound2 python3-cairo python3-flask vlc-nox flite pixz udisks2 raspberrypi-kernel-headers raspberrypi-kernel dkms i2c-tools libasound2-plugins -y

sudo -u pi mkdir /home/pi/SUSI.AI
cd /home/pi/SUSI.AI && sudo -u pi git clone https://github.com/fossasia/susi_linux.git

# Purge Java, try to fix "the trustAnchors parameter must be non-empty" error. Ref: https://askubuntu.com/a/1006748/5871
apt-get purge -y openjdk* java-common ca-certificates-java

# Run SUSI Linux's install script
cd /home/pi/SUSI.AI/susi_linux && git checkout development && sudo -Hu pi ./install.sh

# After ./install.sh, the /dev is occupied by some processes and cannot be released by build script.
# We stop those processes to let the build script continue.

systemctl stop seeed-voicecard
systemctl stop systemd-udevd
sleep 5

#lsof +c0 /dev
#on_chroot << EOF
#systemcl stop systemd-udevd
#EOF
